# Generated by Django 2.1.8 on 2019-06-21 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('position', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('show_on_dashboard', models.BooleanField(default=True)),
                ('show_sparkline', models.BooleanField(default=True)),
                ('unit', models.CharField(max_length=100)),
                ('unit_plural', models.CharField(max_length=100)),
                ('categroy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Category')),
            ],
        ),
    ]
